"""Initializes the graph's state to maintain thread context consistency.

This is basically the communication protocol of the graph's nodes, with it,
it is possible to maintain persistency across the graph's steps. Meaning every 
node knows what the previous did, which defines the next steps.
"""

from typing import Literal, Annotated
from langgraph.graph import MessagesState

def add_docs(existing: list[str], new: list[str]) -> list[str]:
    """Reducer that appends a new document to an existing one.

    This reducer makes sure that the existing documents are not duplicated or
    overwritten by any new documents generated by the Researcher.
    
    Args:
        existing (list[str]): Existing documents.
        new (list[str]): New documents to append.
    
    Returns:
        list[str]: Updated list of documents.
    """
    return existing + new

class ResearchState(MessagesState):
    """
    # Shared state flowing through all graph nodes. 

    Extends `MessagesState` to inherit the messages list with
    its default append reducer.

    Attributes:
        intent: Classified user intent from the Orchestrator
        research_mode: Whether to start a new research or use existing knowledge.
        query: The research query extracted from user input.
        retrieved_docs: Documents retrieved from Chroma.
        cache_hit: Whether relevant context was found in Chroma.
        search_results: List of raw search results from the Researcher.
        final_report: Final report generated by the Writer.
        save_to_chroma: Whether to persist context via HITL.
    """
    intent: Literal["research", "conversation"] 
    research_mode: Literal["new", "existing"] 
    query: str

    # Reducers: instead of overwriting, uses add_docs (e.g. append instead of replace)
    retrieved_docs: Annotated[list[str], add_docs] # reducer for accumulated docs
    search_results: Annotated[list[str], add_docs] # reducer for accumulated search results

    cache_hit: bool 
    final_report: str 
    save_to_chroma: bool 