import chainlit as cl
import os
import sys
import asyncio

if sys.platform == "win32":
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())

from psycopg_pool import AsyncConnectionPool
from langgraph.checkpoint.postgres.aio import AsyncPostgresSaver

from graph import build_graph

DB_URL = os.environ["LANGGRAPH_DATABASE_URL"]
app_graph = None
db_pool = None

@cl.password_auth_callback
async def auth_callback(username: str, password: str):
    if (username == os.getenv("ADMIN_USER") and 
        password == os.getenv("ADMIN_PASS")):
        return cl.User(identifier=username)
    return None

@cl.on_chat_start
async def on_chat_start():
    """Asyncronously starts Chainlit app with graph and DB setup as global variables"""
    
    # Auth
    user = cl.user_session.get("user")
    user_thread = f"{user.identifier}_research_session"
    cl.user_session.set("thread_id", user_thread)

    # Shared throughout the app
    global app_graph, db_pool

    # Only load graph and bd once
    if app_graph is None:

        # Handles async postgres pool conn
        db_pool = AsyncConnectionPool(conninfo=DB_URL, open=False)

        await db_pool.open() # opens bd comms

        # Starts memory management
        checkpointer = AsyncPostgresSaver(db_pool)
        await checkpointer.setup()

        # Builds graph
        app_graph = build_graph(checkpointer)
    
    # Saves unique thread id for user
    cl.user_session.set("thread_id", cl.context.session.id)

    await cl.Message(content=f"Olá {user.identifier}! O que quer pesquisar hoje?").send()

@cl.on_message
async def main(message: cl.Message):
    """Manages the chat messages and agent streaming"""
    # Gets thread ID and sets it as a langgraph config for the checkpointer
    thread_id = cl.user_session.get("thread_id")
    config = {"configurable": {"thread_id": thread_id}}

    # Creates empty streaming object
    msg = cl.Message(content="")
    found_tokens = False

    try:
        # Starts streaming
        async for event in app_graph.astream_events(
            {"messages": [("user", message.content)]},
            config,
            version="v2"
        ):
            # Gets the kind of event
            kind = event["event"]

            # If the kind of event was generated by the LLM
            if kind == "on_chat_model_stream":

                # Verifies which node generated text
                node_name = event["metadata"].get("langgraph_node")

                # Makes sure streaming comes from LLM only
                if node_name in ["writer", "model"]:

                    # Extracts text
                    token = event["data"]["chunk"].content

                    # If exists, set found_tokens to true and stream response
                    if token:
                        found_tokens = True
                        if not msg.id: await msg.send() # empty msg baloon if 1st token 
                        await msg.stream_token(token)

        # Fallback - no tokens streamed
        if not found_tokens:

            # Gets graph's state
            state = await app_graph.aget_state(config)

            # Gets final report (if there's one)
            final_report = state.values.get("final_report")

            # If writer built a report
            if final_report:
                msg.content = final_report
                await msg.send()

            # If it's just a simple message
            else:
                messages = state.values.get("messages", [])
                if messages and messages[-1].type == "ai":
                    msg.content = messages["messages"][-1].content
                await msg.send()

        # If streaming worked, notify chainlit
        else:
            await cl.Message(content="Estou processando sua solicitação, um momento...").send()
    except Exception as e:
        error_msg = f"Ocorreu um erro durante a pesquisa: {str(e)}"
        
        # Updates current msg balloon with error msg
        if msg.id:
            msg.content = error_msg
            await msg.update()
        
        # Creates new msg balloon for error msg
        else:
            await cl.Message(content=error_msg).send()